apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: firebird
  namespace: compufour
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: firebird
        image: jacobalberty/firebird:2.5.8-sc
        imagePullPolicy: Always
        ports:
        - containerPort: 3050
        env:
          - name: ISC_PASSWORD
            value: masterkey
        volumeMounts:
        - mountPath: /firebird/data
          name: volume
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: compufourstorage
