apiVersion: v1
kind: Service
metadata:
  name: firebird
  namespace: compufour
spec:
  type: LoadBalancer
  ports:
  - name: firebird-port
    port: 3050
    targetPort: 3050
  selector:
    app: database
